# Generated by Django 2.2.6 on 2019-12-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
